### ISSUE TITLE
自定义布局

### ISSUE THREAD

**Issue by HelloEasing** [MarkingCode/MiniDialog#1]
有几点建议：
1.可以自己通过API设置失去焦点时，弹窗是否自动关闭
2.增加一个带圆形进度条和说明文字的进度条弹窗
3.弹窗支持自定义布局，比如传入一个html文件，自动将该html布局加载到弹窗内显示

**Comment by MarkingCode** [comment]
您好，感谢您的反馈😊
1. MiniDialog 提供了 Dialog.close() 方法用于在任何情况下手动关闭对话框，您可以根据您的需求在元素失去焦点时调用此方法来关闭对话框；
2. 您所指的是 “loading 加载中” 的效果吗？如果是此效果，那么它已经在开发计划中了，稍后回发布；
3. MiniDialog 参数中的 content 属性支持传入 html 代码，如果有大量的 html 结构可以通过先获取对应元素的 innerHTML ，然后再将结果赋给 content 属性。而对于您所说的 html 文件，个人感觉通过 ajax 请求该文件，然后将返回结果赋值给 content 属性会更好一些，这样还可以在赋值前对数据再次进行处理，更加灵活，同时为了实现最大化自定义效果，可以通过设置 `showTitle: false` 和 `showButton: false` 将标题和底部按钮全部隐藏掉，只保留内容区域，再配合前面的 content 设置，就可以实现最大程度的自定义布局效果了。

以上是我的个人看法，如有理解不对之处或还存有不同意见，还请继续反馈，谢谢！
